camera:
  type: 'c100'
  c100:
    username: "your_username"
    password: "your_password"
    ip_address: "192.168.100.32"
    port: 554
    fps: 15
  minimum_write_frames: 40
files:
  output_dir: out_lit
  output_prefix: lit
  video_file_extension: mp4
motion_detection:
  motion_min_contour_area: 2500
  warmup_seconds: 2.0
  detection_persistance:
    memory_size: 150
    activation_detection_ratio_threshold: 0.0
    deactivation_detection_ratio_threshold: 0.1
drive:
  enabled: False
  client_json_file_path: '/workspaces/lit-checker/configs/config.json'
  google_drive_root_folder: 'lit-checker'
mail:
  account:
    address: 'account@gmail.com'
    to_address: 'account@gmail.com'
    password: 'password'
log:
  level: info
  log_file_name: 'log.txt'